### ISSUE TITLE
ImportError: cannot import name 'NSMLWriter' from 'base.utils.writer'

### ISSUE THREAD

**Issue by ammar-deep** [clovaai/fewshot-font-generation#1]
Hi thanks for providing this FFG framework.

I am trying to run MXFont on a custom Korean dataset. When I run the training command I get the following error **"ImportError: cannot import name 'NSMLWriter' from 'base.utils.writer'"** 

I removed the 'NSMLWriter' import and its second reference from the `'base/utils/__init__.py '` file and now its working fine. 

1) Do we really need 'NSMLWriter'? 
2) Seems like the framework only supports grayscale images (not RGB as I got a channel error with RGB dataset). Can we train with RGB  character images?

**Comment by SanghyukChun** [comment]
Oops, nsml is the name of an internal GPU platform system of NAVER. It should be deleted sorry. We will update the code as soon as possible.

Our method is built upon grayscale because we only consider true-type fonts (ttf) as inputs. You can change it to RGB by changing the dataset code and the input interface. But it is actually meaningless if you still use ttf as input.

**Comment by ammar-deep** [comment]
Ok Great.
Thanks
